# Generated by Django 3.1 on 2020-10-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch_related',
            field=models.ManyToManyField(to='auctions.Watchlist'),
        ),
    ]
