# Generated by Django 3.1 on 2020-10-12 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_watch_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watch_related',
        ),
        migrations.AddField(
            model_name='listing',
            name='who_want_buy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
