# Generated by Django 3.1 on 2020-10-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201013_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item_bid',
            new_name='item_bid_id',
        ),
    ]
