# Generated by Django 3.1 on 2020-10-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201014_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item_bid_id',
            new_name='item_bid',
        ),
    ]
