# Generated by Django 3.1 on 2020-10-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201014_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
