# Generated by Django 3.1 on 2020-10-17 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20201017_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to=settings.AUTH_USER_MODEL),
        ),
    ]
