# Generated by Django 3.1 on 2020-10-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
    ]
