# Generated by Django 3.1 on 2020-10-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20201018_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
    ]
